use client";

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'VentaFacil App',
  description: 'Generated by VictorDiaz',
};

import React from 'react';

interface Props {
    children: React.ReactNode
}
const Layout = ({ children }: Props) => {
    return (
        <>
            {children}
        </>
    );
};

export default Layout;
