use client";

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'VentaFacil App',
  description: 'Generated by Firebase Studio',
};

import React from 'react';

interface Props {
    children: React.ReactNode
}
const Layout = ({ children }: Props) => {
    return (
        <html lang="en">
            {children}
        </html>
    );
};

export default Layout;

