import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Menubar, MenubarContent, MenubarItem, MenubarMenu, MenubarTrigger} from '@/components/ui/menubar';
import {Home, Plus, Settings, ShoppingCart} from "lucide-react";
import { Icons } from '@/components/icons';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header className="bg-secondary p-4">
          <Menubar>
            <MenubarMenu>
              <MenubarTrigger>
                <Home className="mr-2 h-4 w-4" />
                Home
              </MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  <a href="/">Dashboard</a>
                </MenubarItem>
              </MenubarContent>
            </MenubarMenu>
            <MenubarMenu>
              <MenubarTrigger>
                <Plus className="mr-2 h-4 w-4" />
                Generate
              </MenubarTrigger>
              <MenubarContent>
                <MenubarItem>
                  <a href="/inventory">Inventory</a>
                </MenubarItem>
                 <MenubarItem>
                  <a href="/sales">Sales</a>
                </MenubarItem>
                  <MenubarItem>
                  <a href="/pedidos">Pedidos</a>
                </MenubarItem>
              </MenubarContent>
            </MenubarMenu>
           
            <MenubarMenu>
              <MenubarTrigger>
                <Settings className="mr-2 h-4 w-4" />
                Settings
              </MenubarTrigger>
              <MenubarContent>
                <MenubarItem>Profile</MenubarItem>
                <MenubarItem>Preferences</MenubarItem>
              </MenubarContent>
            </MenubarMenu>
          </Menubar>
        </header>
        {children}
      </body>
    </html>
  );
}
